apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaming-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/teachers-lounge/teachers-lounge.git
    targetRevision: main
    path: infra/helm/gaming-service
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
