replicaCount: 3

image:
  tag: stable

ingress:
  host: app.teacherslounge.app

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
