apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
  selector:
    {{- include "qdrant.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.fullname" . }}-headless
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 6333
    - name: grpc
      port: 6334
    - name: p2p
      port: 6335
  selector:
    {{- include "qdrant.selectorLabels" . | nindent 4 }}
