replicaCount: 1
image:
  tag: dev
env:
  AI_GATEWAY_URL: "http://ai-gateway.dev.svc.cluster.local:4000"
  USER_SERVICE_URL: "http://user-service.dev.svc.cluster.local:8080"
  DB_HOST: "postgres.dev.svc.cluster.local"
  REDIS_HOST: "redis.dev.svc.cluster.local"
  LOG_LEVEL: "debug"
