'use client'

import { useCallback, useState } from 'react'

// ── Types ─────────────────────────────────────────────────────────────────────

/** A single structured note entry. */
export interface NoteEntry {
  /** Entry type — determines icon, label, and Anki export eligibility. */
  type: 'definition' | 'rule' | 'example' | 'flashcard'
  /** The term, question, or rule name. */
  term: string
  /** Expanded body: definition text, rule statement, example, or answer. */
  body: string
}

interface Props {
  /** Ordered list of note entries generated by the tutor. */
  notes: NoteEntry[]
  /**
   * Called when the student clicks an export button.
   * Receives the format name and the serialised string ready to download.
   */
  onExport?: (format: 'markdown' | 'anki', content: string) => void
}

// ── Label map ─────────────────────────────────────────────────────────────────

const TYPE_LABEL: Record<NoteEntry['type'], string> = {
  definition: 'DEF',
  rule: 'RULE',
  example: 'EX',
  flashcard: 'CARD',
}

const TYPE_COLOR: Record<NoteEntry['type'], string> = {
  definition: 'text-neon-blue border-neon-blue/40 bg-neon-blue/10',
  rule: 'text-neon-pink border-neon-pink/40 bg-neon-pink/10',
  example: 'text-neon-green border-neon-green/40 bg-neon-green/10',
  flashcard: 'text-neon-gold border-neon-gold/40 bg-neon-gold/10',
}

// ── Export utilities ──────────────────────────────────────────────────────────

/**
 * Serialise notes to a Markdown string.
 *
 * Each entry is rendered as a definition-list block under a `## Notes` heading.
 * Type labels are shown as bold prefixes.
 *
 * @param notes - Array of note entries to serialise.
 * @returns Markdown string, or empty string if notes is empty.
 */
export function exportAsMarkdown(notes: NoteEntry[]): string {
  if (notes.length === 0) return ''
  const lines: string[] = ['# Notes', '']
  for (const n of notes) {
    lines.push(`**[${TYPE_LABEL[n.type]}] ${n.term}**`)
    lines.push('')
    lines.push(n.body)
    lines.push('')
  }
  return lines.join('\n')
}

/**
 * Serialise notes to an Anki-compatible CSV string.
 *
 * The CSV uses a tab separator to avoid conflicts with commas in chemistry
 * formulae.  All entries are included (front = term, back = body).
 *
 * @param notes - Array of note entries to serialise.
 * @returns CSV string with header row followed by one data row per entry.
 */
export function exportAsAnkiCsv(notes: NoteEntry[]): string {
  const rows: string[] = ['Front\tBack']
  for (const n of notes) {
    const front = n.term.replace(/\t/g, ' ')
    const back = n.body.replace(/\t/g, ' ')
    rows.push(`${front}\t${back}`)
  }
  return rows.join('\n')
}

// ── FlashCard ─────────────────────────────────────────────────────────────────

/**
 * Single flip-card for flashcard-type note entries.
 * Clicking toggles between the term (front) and body (back).
 */
function FlashCard({ entry }: { entry: NoteEntry }) {
  const [flipped, setFlipped] = useState(false)

  return (
    <button
      onClick={() => setFlipped((f) => !f)}
      aria-label="Flip card"
      className="w-full text-left px-3 py-2.5 rounded-lg border border-neon-gold/30 bg-neon-gold/5 hover:bg-neon-gold/10 transition-colors cursor-pointer"
    >
      <div className="flex items-center gap-2 mb-1">
        <span className="text-[9px] font-mono font-bold px-1 py-0.5 rounded border text-neon-gold border-neon-gold/40 bg-neon-gold/10">
          CARD
        </span>
        <span className="text-[10px] font-mono text-neon-gold">
          {flipped ? 'ANSWER' : 'QUESTION'}
        </span>
      </div>
      <div className="text-sm text-text-base leading-snug">{flipped ? entry.body : entry.term}</div>
      <div className="text-[9px] text-text-dim mt-1.5">
        (click to {flipped ? 'see question' : 'reveal answer'})
      </div>
    </button>
  )
}

// ── NoteRow ───────────────────────────────────────────────────────────────────

/**
 * Renders a single non-flashcard note entry as a definition/rule/example row.
 */
function NoteRow({ entry }: { entry: NoteEntry }) {
  return (
    <div className="flex gap-2.5">
      <span
        className={`flex-shrink-0 text-[9px] font-mono font-bold px-1 py-0.5 rounded border self-start mt-0.5 ${TYPE_COLOR[entry.type]}`}
      >
        {TYPE_LABEL[entry.type]}
      </span>
      <div className="flex-1 min-w-0">
        <div className="text-xs font-semibold text-text-bright leading-snug">{entry.term}</div>
        <div className="text-xs text-text-base mt-0.5 leading-relaxed">{entry.body}</div>
      </div>
    </div>
  )
}

// ── NotesPanel ────────────────────────────────────────────────────────────────

/**
 * Structured notes panel for read/write learner mode.
 *
 * Displays tutor-generated definitions, rules, examples, and flashcards.
 * Flashcard entries are interactive flip-cards.
 * Export buttons (Markdown, Anki) call the onExport callback when present.
 */
export default function NotesPanel({ notes, onExport }: Props) {
  const handleMarkdown = useCallback(() => {
    onExport?.('markdown', exportAsMarkdown(notes))
  }, [notes, onExport])

  const handleAnki = useCallback(() => {
    onExport?.('anki', exportAsAnkiCsv(notes))
  }, [notes, onExport])

  return (
    <div className="flex flex-col gap-2 p-3 bg-bg-card border border-border-mid rounded-xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-xs font-mono font-bold text-text-bright uppercase tracking-widest">
          Notes
        </h3>
        {onExport && (
          <div className="flex gap-1.5">
            <button
              onClick={handleMarkdown}
              aria-label="Export as Markdown"
              className="px-2 py-0.5 text-[10px] font-mono border border-border-dim text-text-dim rounded hover:border-border-mid transition-colors"
            >
              Markdown
            </button>
            <button
              onClick={handleAnki}
              aria-label="Export as Anki"
              className="px-2 py-0.5 text-[10px] font-mono border border-border-dim text-text-dim rounded hover:border-border-mid transition-colors"
            >
              Anki
            </button>
          </div>
        )}
      </div>

      {/* Divider */}
      <div className="h-px bg-border-dim" />

      {/* Entries */}
      {notes.length === 0 ? (
        <p className="text-xs text-text-dim italic">No notes yet.</p>
      ) : (
        <div className="flex flex-col gap-3">
          {notes.map((entry, i) =>
            entry.type === 'flashcard' ? (
              <FlashCard key={i} entry={entry} />
            ) : (
              <NoteRow key={i} entry={entry} />
            ),
          )}
        </div>
      )}
    </div>
  )
}
