apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.datasources.prometheusUrl }}
        isDefault: true
        editable: false
      - name: Jaeger
        type: jaeger
        access: proxy
        url: {{ .Values.datasources.jaegerUrl }}
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: TeachersLounge
        orgId: 1
        folder: TeachersLounge
        type: file
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
