-- Migration 006: seed scifi_quotes with 225 curated quotes across 9 context types.
-- Context values: session_start | boss_fight | correct | wrong | victory | defeat | streak | achievement | comeback

INSERT INTO scifi_quotes (quote, attribution, context) VALUES

-- ── session_start (25 quotes) ──────────────────────────────────────────────
('The spice must flow.', 'Gurney Halleck — Dune', 'session_start'),
('Fear is the mind-killer.', 'Paul Atreides — Dune', 'session_start'),
('I must not fear. Fear is the mind-killer.', 'Bene Gesserit Litany — Dune', 'session_start'),
('In the beginning was the word, and the word was with the computer.', 'Hitchhiker''s Guide to the Galaxy', 'session_start'),
('The answer to life, the universe, and everything is 42.', 'Deep Thought — The Hitchhiker''s Guide to the Galaxy', 'session_start'),
('I am not a number — I am a free man!', 'Number Six — The Prisoner', 'session_start'),
('Live long and prosper.', 'Mr. Spock — Star Trek', 'session_start'),
('Space: the final frontier.', 'Captain Kirk — Star Trek', 'session_start'),
('Engage.', 'Captain Picard — Star Trek: TNG', 'session_start'),
('Make it so.', 'Captain Picard — Star Trek: TNG', 'session_start'),
('The Force will be with you. Always.', 'Obi-Wan Kenobi — Star Wars', 'session_start'),
('Do or do not — there is no try.', 'Yoda — Star Wars: The Empire Strikes Back', 'session_start'),
('There is no spoon.', 'Spoon Boy — The Matrix', 'session_start'),
('Wake up, Neo...', 'Trinity — The Matrix', 'session_start'),
('It''s a dangerous business, going out your door.', 'Bilbo Baggins — The Lord of the Rings', 'session_start'),
('Every battle is won before it''s ever fought.', 'Ender Wiggin — Ender''s Game', 'session_start'),
('The enemy''s gate is down.', 'Ender Wiggin — Ender''s Game', 'session_start'),
('We are the Borg. Resistance is futile.', 'The Borg — Star Trek: TNG', 'session_start'),
('I''ll be back.', 'The Terminator — The Terminator', 'session_start'),
('To infinity and beyond!', 'Buzz Lightyear — Toy Story', 'session_start'),
('The truth is out there.', 'Fox Mulder — The X-Files', 'session_start'),
('In the future, everyone will be world-famous for fifteen minutes.', 'Andy Warhol', 'session_start'),
('Mathematics is the language in which God has written the universe.', 'Galileo Galilei', 'session_start'),
('Equipped with his five senses, man explores the universe around him and calls the adventure Science.', 'Edwin Hubble', 'session_start'),
('The cosmos is within us. We are made of star-stuff.', 'Carl Sagan — Cosmos', 'session_start'),

-- ── boss_fight (25 quotes) ────────────────────────────────────────────────
('I find your lack of faith disturbing.', 'Darth Vader — Star Wars: A New Hope', 'boss_fight'),
('You were meant to destroy the Sith, not join them!', 'Obi-Wan Kenobi — Revenge of the Sith', 'boss_fight'),
('I am your father.', 'Darth Vader — Star Wars: The Empire Strikes Back', 'boss_fight'),
('You cannot pass!', 'Gandalf — The Lord of the Rings: The Fellowship of the Ring', 'boss_fight'),
('None shall pass.', 'Black Knight — Monty Python and the Holy Grail', 'boss_fight'),
('I''m going to make him an offer he can''t refuse.', 'Vito Corleone — The Godfather', 'boss_fight'),
('I''ve been waiting for you, Obi-Wan. We meet again, at last.', 'Darth Vader — A New Hope', 'boss_fight'),
('At last we will reveal ourselves to the Jedi.', 'Darth Maul — Star Wars: The Phantom Menace', 'boss_fight'),
('Hasta la vista, baby.', 'T-800 — Terminator 2: Judgment Day', 'boss_fight'),
('You think darkness is your ally?', 'Bane — The Dark Knight Rises', 'boss_fight'),
('I''ve had worse.', 'Riddick — Pitch Black', 'boss_fight'),
('I am the danger.', 'Walter White — Breaking Bad', 'boss_fight'),
('You want the truth? You can''t handle the truth!', 'Col. Jessup — A Few Good Men', 'boss_fight'),
('I have been, and always shall be, your friend.', 'Spock — Star Trek II: The Wrath of Khan', 'boss_fight'),
('The needs of the many outweigh the needs of the few.', 'Spock — Star Trek II: The Wrath of Khan', 'boss_fight'),
('Resistance is futile.', 'The Borg — Star Trek: First Contact', 'boss_fight'),
('Run, you fools!', 'Gandalf — The Lord of the Rings', 'boss_fight'),
('You shall not pass!', 'Gandalf — The Lord of the Rings: The Fellowship of the Ring', 'boss_fight'),
('There is no escape. Don''t make me destroy you.', 'Darth Vader — The Empire Strikes Back', 'boss_fight'),
('I am inevitable.', 'Thanos — Avengers: Endgame', 'boss_fight'),
('And I... am Iron Man.', 'Tony Stark — Avengers: Endgame', 'boss_fight'),
('Dormammu, I''ve come to bargain.', 'Doctor Strange — Doctor Strange', 'boss_fight'),
('On your left.', 'Sam Wilson — Avengers: Endgame', 'boss_fight'),
('We''re in the endgame now.', 'Doctor Strange — Avengers: Infinity War', 'boss_fight'),
('Whatever it takes.', 'Tony Stark — Avengers: Endgame', 'boss_fight'),

-- ── correct (25 quotes) ───────────────────────────────────────────────────
('Excellent!', 'Mr. Burns — The Simpsons', 'correct'),
('Logical.', 'Mr. Spock — Star Trek', 'correct'),
('Affirmative. That computation is correct.', 'HAL 9000 — 2001: A Space Odyssey', 'correct'),
('You''ve just taken your first step into a larger world.', 'Obi-Wan Kenobi — Star Wars', 'correct'),
('The Force is strong with this one.', 'Darth Vader — Star Wars', 'correct'),
('Well done, Grasshopper.', 'Master Po — Kung Fu', 'correct'),
('Shiny.', 'Mal Reynolds — Firefly', 'correct'),
('A wizard is never late, nor is he early — he arrives precisely when he means to.', 'Gandalf — The Lord of the Rings', 'correct'),
('Elementary, my dear Watson.', 'Sherlock Holmes', 'correct'),
('I knew you had the stuff.', 'Major Silva — Ender''s Game', 'correct'),
('You have the makings of a true commander.', 'Mazer Rackham — Ender''s Game', 'correct'),
('Correct. You are a quick study.', 'Galadriel — The Lord of the Rings', 'correct'),
('Your mind is a formidable instrument.', 'Spock — Star Trek', 'correct'),
('That answer resonates with the Force.', 'Master Yoda — Star Wars', 'correct'),
('Outstanding! You have outperformed my projections.', 'Skynet — Terminator 2 (fan adaptation)', 'correct'),
('You begin to see as I see.', 'Arrakis Oracle — Dune', 'correct'),
('The answer is as clear as dilithium crystals.', 'Scotty — Star Trek', 'correct'),
('My calculations confirm your reasoning.', 'C-3PO — Star Wars', 'correct'),
('Your logic is sound.', 'Data — Star Trek: TNG', 'correct'),
('Impressive. Most impressive.', 'Darth Vader — The Empire Strikes Back', 'correct'),
('Now you are thinking with portals.', 'GLaDOS — Portal', 'correct'),
('A sound conclusion. The council is pleased.', 'Mace Windu — Star Wars', 'correct'),
('I have no doubt you''ll make an excellent commander someday.', 'Colonel Graff — Ender''s Game', 'correct'),
('You surprise me. That is not easy to do.', 'Morpheus — The Matrix', 'correct'),
('You are beginning to believe.', 'Morpheus — The Matrix', 'correct'),

-- ── wrong (25 quotes) ─────────────────────────────────────────────────────
('That is not the answer I expected.', 'HAL 9000 — 2001: A Space Odyssey', 'wrong'),
('I''m sorry, Dave. I''m afraid I can''t do that.', 'HAL 9000 — 2001: A Space Odyssey', 'wrong'),
('Try again.', 'Yoda — Star Wars', 'wrong'),
('You will learn or you will not.', 'Mazer Rackham — Ender''s Game', 'wrong'),
('Anger leads to the dark side.', 'Yoda — Star Wars', 'wrong'),
('Logic clearly dictates that the needs of recalibration outweigh the embarrassment.', 'Spock — Star Trek', 'wrong'),
('Recalculating...', 'GPS Voice — Every Road Trip', 'wrong'),
('That is not what I would call optimal.', 'Data — Star Trek: TNG', 'wrong'),
('Your logic is flawed, but that is a place to start.', 'Vulcan Elder — Star Trek', 'wrong'),
('Hmm. Not quite. Let us reason through it together.', 'Gandalf — The Lord of the Rings', 'wrong'),
('A small step backward to take a larger one forward.', 'Paul Muad''Dib — Dune', 'wrong'),
('The mind bends before it breaks. Try again.', 'Bene Gesserit — Dune', 'wrong'),
('That was not the expected result. Fascinating.', 'Spock — Star Trek', 'wrong'),
('Close, but in space, close only counts with horseshoes and hand grenades.', 'Astronaut saying', 'wrong'),
('Almost. We''ll get there.', 'Mal Reynolds — Firefly', 'wrong'),
('I''ve made a huge mistake.', 'Gob Bluth — Arrested Development', 'wrong'),
('We shall not speak of this again.', 'Darth Vader — Star Wars', 'wrong'),
('Your brain is like a supercomputer — sometimes it needs a reboot.', 'GLaDOS — Portal', 'wrong'),
('Failure is just success in progress.', 'Thomas Edison', 'wrong'),
('Every wrong answer eliminates one possibility.', 'Sherlock Holmes (adapted)', 'wrong'),
('The first step to wisdom is knowing what you do not know.', 'Confucius', 'wrong'),
('Your potential is unquestionable. Your knowledge needs updating.', 'Mazer Rackham — Ender''s Game', 'wrong'),
('We do not learn from success alone.', 'Morpheus — The Matrix', 'wrong'),
('Reset. Recalibrate. Return.', 'GLaDOS — Portal 2', 'wrong'),
('That which does not compute makes us recalculate.', 'Spock — Star Trek', 'wrong'),

-- ── victory (25 quotes) ───────────────────────────────────────────────────
('It''s a trap! — Wait, no — we won!', 'Admiral Ackbar — Star Wars: Return of the Jedi', 'victory'),
('I knew you could do it.', 'R2-D2 (translated) — Star Wars', 'victory'),
('You''ve earned your place at the table.', 'Colonel Graff — Ender''s Game', 'victory'),
('The training is over. You are ready.', 'Morpheus — The Matrix', 'victory'),
('Victory is mine!', 'Stewie Griffin — Family Guy', 'victory'),
('I am a leaf on the wind — watch how I soar.', 'Wash — Firefly', 'victory'),
('Beam me up — with honors.', 'Captain Kirk — Star Trek', 'victory'),
('You have passed the test.', 'Mazer Rackham — Ender''s Game', 'victory'),
('Well done! Well done, indeed.', 'Dumbledore — Harry Potter', 'victory'),
('The simulation has been completed successfully.', 'GLaDOS — Portal 2', 'victory'),
('Today is a good day to succeed.', 'Worf — Star Trek: TNG', 'victory'),
('Not bad, for a human.', 'Chewbacca (translated) — Star Wars', 'victory'),
('You did it! You crazy son of a... you did it.', 'Commander Hadfield — ISS', 'victory'),
('By Grabthar''s hammer, what a victory.', 'Dr. Lazarus — Galaxy Quest', 'victory'),
('There is no greater satisfaction than mastery.', 'Paul Muad''Dib — Dune', 'victory'),
('We have fought, and we have won.', 'Ender Wiggin — Ender''s Game', 'victory'),
('You are the one.', 'Oracle — The Matrix', 'victory'),
('You have altered the course of history for the better.', 'Guinan — Star Trek: TNG', 'victory'),
('Your journey to the light side is complete.', 'Emperor Palpatine — Star Wars (ironically)', 'victory'),
('To boldly go where no one has gone before — and succeed.', 'Captain Picard — Star Trek', 'victory'),
('It is done.', 'Thanos — Avengers: Infinity War', 'victory'),
('Avengers... assemble.', 'Captain America — Avengers: Endgame', 'victory'),
('I am Groot.', 'Groot — Guardians of the Galaxy', 'victory'),
('I told you so. Now take a bow.', 'Tony Stark — Avengers', 'victory'),
('The universe bows to the victorious mind.', 'Foundation — Isaac Asimov', 'victory'),

-- ── defeat (25 quotes) ────────────────────────────────────────────────────
('I have failed you.', 'Anakin Skywalker — Star Wars: Revenge of the Sith', 'defeat'),
('You underestimate the power of the dark side.', 'Darth Vader — Star Wars', 'defeat'),
('Even the strongest fall.', 'Mazer Rackham — Ender''s Game', 'defeat'),
('You have failed this city.', 'Green Arrow — Arrow', 'defeat'),
('The needs of the many... I am sorry, friend.', 'Spock — Star Trek II', 'defeat'),
('We cannot win every battle, only the war.', 'Paul Muad''Dib — Dune', 'defeat'),
('Failure is the great teacher.', 'Yoda — Star Wars', 'defeat'),
('The wound is where the light enters you.', 'Rumi (adapted for space)', 'defeat'),
('Every defeat is a lesson waiting to be learned.', 'Gandalf — The Lord of the Rings', 'defeat'),
('Not all who wander are lost — some just need to try again.', 'J.R.R. Tolkien (adapted)', 'defeat'),
('I have walked this path before. I know the way back.', 'Doctor Strange — Marvel', 'defeat'),
('This is not the end. It is not even the beginning of the end.', 'Winston Churchill (adapted)', 'defeat'),
('You cannot fail if you refuse to quit.', 'Morpheus — The Matrix', 'defeat'),
('The simulation will reset. Try again.', 'GLaDOS — Portal', 'defeat'),
('You still have time. Use it wisely.', 'Colonel Graff — Ender''s Game', 'defeat'),
('What is essential is invisible to the eye. Maybe you haven''t found it yet.', 'The Little Prince', 'defeat'),
('Even stars burn out before they shine brightest.', 'Foundation — Isaac Asimov', 'defeat'),
('A temporary setback on the path to understanding.', 'Spock — Star Trek', 'defeat'),
('Kneel before knowledge — and rise prepared.', 'Bene Gesserit — Dune', 'defeat'),
('I have died more times than I can count. I always come back stronger.', 'Doctor Strange — What If...?', 'defeat'),
('Losing teaches what winning cannot.', 'Mazer Rackham — Ender''s Game', 'defeat'),
('The Jedi do not grieve their defeats — they learn from them.', 'Mace Windu — Star Wars', 'defeat'),
('It is a poor craftsman who blames his tools. Sharpen yourself.', 'Vulcan Proverb — Star Trek', 'defeat'),
('You have not failed until you stop trying.', 'Data — Star Trek: TNG', 'defeat'),
('Tomorrow you will be better. Today was the cost.', 'Firefly adapted', 'defeat'),

-- ── streak (25 quotes) ────────────────────────────────────────────────────
('Consistency is the foundation of all mastery.', 'Morpheus — The Matrix (adapted)', 'streak'),
('There is no power in all the universe that can stop me now.', 'Ender Wiggin — Ender''s Game', 'streak'),
('Your training has been exceptional.', 'Colonel Graff — Ender''s Game', 'streak'),
('The spice of consistency flows through you.', 'Reverend Mother — Dune', 'streak'),
('Every day you return, you become more than you were.', 'Yoda — Star Wars', 'streak'),
('Persistence is the hallmark of genius.', 'Albert Einstein (adapted)', 'streak'),
('Seven days of learning. The universe bends to the committed.', 'Foundation — Isaac Asimov', 'streak'),
('You have not missed a day. That is... impressive.', 'Darth Vader — Star Wars', 'streak'),
('The relentless march of knowledge — that is your streak.', 'Spock — Star Trek', 'streak'),
('Pattern recognized: exceptional.', 'HAL 9000 — 2001: A Space Odyssey', 'streak'),
('You show up. Day after day. That is a superpower.', 'Tony Stark — Avengers', 'streak'),
('Staying the course requires more courage than starting it.', 'Paul Muad''Dib — Dune', 'streak'),
('A warrior trains every day, without exception.', 'Mazer Rackham — Ender''s Game', 'streak'),
('On and on, the engines of learning never stop.', 'Scotty — Star Trek', 'streak'),
('You are building something that will outlast a single session.', 'Gandalf — The Lord of the Rings', 'streak'),
('Momentum is the closest thing to magic that physics allows.', 'Richard Feynman (adapted)', 'streak'),
('The difference between amateur and master is ten thousand hours of showing up.', 'Sensei saying', 'streak'),
('Day after day, the mind rewires itself in your favor.', 'Foundation — Isaac Asimov', 'streak'),
('Persistence defeats resistance, every time.', 'Firefly adapted', 'streak'),
('Your neural pathways are strengthening with each session. I approve.', 'HAL 9000 — 2001: A Space Odyssey', 'streak'),
('I respect consistency above all other virtues.', 'Sarek — Star Trek', 'streak'),
('The drip of water carves the stone — so does daily study.', 'Bene Gesserit — Dune', 'streak'),
('You are becoming impossible to stop.', 'Nick Fury — Avengers', 'streak'),
('The streak is a testament to who you are becoming.', 'Morpheus — The Matrix', 'streak'),
('Come back tomorrow. Be even stronger.', 'GLaDOS — Portal', 'streak'),

-- ── achievement (25 quotes) ───────────────────────────────────────────────
('Achievement unlocked: Beyond All Expectations.', 'GLaDOS — Portal', 'achievement'),
('You have become more powerful than I could possibly have imagined.', 'Obi-Wan Kenobi — Star Wars', 'achievement'),
('The student has surpassed the master.', 'Gandalf — The Lord of the Rings', 'achievement'),
('I never thought I''d see someone do that.', 'Scotty — Star Trek', 'achievement'),
('You have impressed even the gods.', 'Foundation — Isaac Asimov', 'achievement'),
('History will remember this day.', 'Picard — Star Trek', 'achievement'),
('This achievement will be recorded in the archives of Battle School.', 'Colonel Graff — Ender''s Game', 'achievement'),
('You have unlocked something rare — genuine mastery.', 'Morpheus — The Matrix', 'achievement'),
('All the training, all the sacrifice — it was worth it.', 'Katniss Everdeen — The Hunger Games', 'achievement'),
('Consider yourself Legendary.', 'Nick Fury — Avengers (adapted)', 'achievement'),
('You have altered the simulation beyond its designed parameters.', 'GLaDOS — Portal 2', 'achievement'),
('The universe acknowledges your excellence.', 'Spock — Star Trek', 'achievement'),
('Even I am surprised. That does not happen often.', 'Sherlock Holmes (adapted)', 'achievement'),
('You have earned this moment. Now use it to go further.', 'Mazer Rackham — Ender''s Game', 'achievement'),
('Remarkable. Truly remarkable.', 'Data — Star Trek: TNG', 'achievement'),
('The Force recognizes your achievement.', 'Yoda — Star Wars', 'achievement'),
('You have done what many believed impossible.', 'Gandalf — The Lord of the Rings', 'achievement'),
('That which was hidden is now revealed through your effort.', 'Bene Gesserit — Dune', 'achievement'),
('The stars themselves bear witness to your achievement.', 'Carl Sagan — Cosmos (adapted)', 'achievement'),
('Not just done — done brilliantly.', 'Wash — Firefly', 'achievement'),
('I knew from the beginning you were different.', 'Colonel Graff — Ender''s Game', 'achievement'),
('The data logs will reflect this as an exceptional event.', 'HAL 9000 — 2001: A Space Odyssey', 'achievement'),
('Heroes are not born; they are compiled.', 'Alan Turing (adapted)', 'achievement'),
('You have proven the simulation wrong.', 'Morpheus — The Matrix', 'achievement'),
('Level complete. You are now something else entirely.', 'GLaDOS — Portal', 'achievement'),

-- ── comeback (25 quotes) ──────────────────────────────────────────────────
('I''m still standing.', 'Elton John (adapted for space)', 'comeback'),
('You came back. That tells me everything I need to know.', 'Mazer Rackham — Ender''s Game', 'comeback'),
('Rise.', 'Alfred Pennyworth — The Dark Knight Rises', 'comeback'),
('It''s not over until I say it''s over.', 'Captain America — Avengers', 'comeback'),
('The greatest glory in living lies not in never falling, but in rising every time.', 'Nelson Mandela', 'comeback'),
('I have come back from the dead. This is nothing.', 'Doctor Strange — Marvel', 'comeback'),
('Returning after absence shows true dedication.', 'Colonel Graff — Ender''s Game', 'comeback'),
('The Force has brought you back. Listen to it.', 'Obi-Wan Kenobi — Star Wars', 'comeback'),
('Against all odds, you returned. Respect.', 'Nick Fury — Avengers', 'comeback'),
('Welcome back. The mission awaits.', 'Morpheus — The Matrix', 'comeback'),
('Fall seven times, stand up eight.', 'Japanese Proverb', 'comeback'),
('We never lost faith in you. Glad you''re back.', 'Picard — Star Trek: TNG', 'comeback'),
('The spice still flows. You have returned.', 'Duncan Idaho — Dune', 'comeback'),
('A true soldier always finds the way back.', 'Mazer Rackham — Ender''s Game', 'comeback'),
('Darkness could not keep you. That is power.', 'Galadriel — The Lord of the Rings', 'comeback'),
('The simulation was on pause, not cancelled.', 'GLaDOS — Portal', 'comeback'),
('You are the proof that setbacks are just setups.', 'Tony Stark — Avengers', 'comeback'),
('Resuming trajectory.', 'HAL 9000 — 2001: A Space Odyssey', 'comeback'),
('I''ve seen comets return that burned less bright.', 'Foundation — Isaac Asimov', 'comeback'),
('Even the tardiest student can outrun a sitting scholar.', 'Bene Gesserit — Dune', 'comeback'),
('Absence makes the mind grow hungrier.', 'Carl Sagan (adapted)', 'comeback'),
('Back from the outer rim. Welcome, traveler.', 'Firefly adapted', 'comeback'),
('You have returned to yourself. That is no small thing.', 'Yoda — Star Wars', 'comeback'),
('All timelines lead back to this moment.', 'Doctor Strange — What If...?', 'comeback'),
('The battle continues. And you are here for it.', 'Ender Wiggin — Ender''s Game', 'comeback');
